name: tanks_app
description: TANKS APP
version: 1.0.1
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  failures:
    path: packages/failures
  intl: ^0.19.0
  get_it: ^8.0.0
  equatable: ^2.0.5
  tank_repository:
    path: packages/tank_repository
  toggle_switch: ^2.3.0
  collection: ^1.18.0
  elegant_notification: ^2.3.0
  tank_database:
    path: packages/tank_database
  lottie: ^3.1.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  fluentui_system_icons: ^1.1.259
  const_date_time: ^1.1.0
  syncfusion_flutter_charts: ^27.1.51
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/
