name: tanks_app
description: TANKS APP
version: 1.0.1
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  failures:
    path: packages/failures
  intl: ^0.19.0
  get_it: ^8.0.0
  equatable: ^2.0.5
  tank_repository:
    path: packages/tank_repository
  toggle_switch: ^2.3.0
  collection: ^1.18.0
  elegant_notification: ^2.3.0
  tank_database:
    path: packages/tank_database
  lottie: ^3.1.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  fluentui_system_icons: ^1.1.259
  const_date_time: ^1.1.0
  fl_chart: ^0.66.0
  kdgaugeview: ^1.0.5
  percent_indicator: ^4.2.3
  dropdown_button2: ^2.3.9
  flutter_colorpicker: ^1.1.0
  firebase_messaging: ^15.1.0
  firebase_core: ^3.4.0
  flutter_local_notifications: ^17.2.3
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/
    - assets/img/
