// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYmsnr1mNmcRi7mNmp8lkqbIcfGHQwMTs',
    appId: '1:996411179077:web:e6a40ea15f4fda66f0632c',
    messagingSenderId: '996411179077',
    projectId: 'tanks-app-f13f6',
    authDomain: 'tanks-app-f13f6.firebaseapp.com',
    storageBucket: 'tanks-app-f13f6.appspot.com',
    measurementId: 'G-BDWKYENK1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz2aORAjT6_j3aiWmlXSd1pN_wdrLuKCU',
    appId: '1:996411179077:android:7a4137ed32ab2882f0632c',
    messagingSenderId: '996411179077',
    projectId: 'tanks-app-f13f6',
    storageBucket: 'tanks-app-f13f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-c9L4hA2LkSRMRmqf7FUHgDwGfDH7npo',
    appId: '1:996411179077:ios:fa16cdfe0c0b264bf0632c',
    messagingSenderId: '996411179077',
    projectId: 'tanks-app-f13f6',
    storageBucket: 'tanks-app-f13f6.appspot.com',
    iosBundleId: 'com.example.tanksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-c9L4hA2LkSRMRmqf7FUHgDwGfDH7npo',
    appId: '1:996411179077:ios:fa16cdfe0c0b264bf0632c',
    messagingSenderId: '996411179077',
    projectId: 'tanks-app-f13f6',
    storageBucket: 'tanks-app-f13f6.appspot.com',
    iosBundleId: 'com.example.tanksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYmsnr1mNmcRi7mNmp8lkqbIcfGHQwMTs',
    appId: '1:996411179077:web:6c0024a7e3f3d280f0632c',
    messagingSenderId: '996411179077',
    projectId: 'tanks-app-f13f6',
    authDomain: 'tanks-app-f13f6.firebaseapp.com',
    storageBucket: 'tanks-app-f13f6.appspot.com',
    measurementId: 'G-Z99GYRHZR1',
  );
}
