name: tank_database
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  failures:
    path: ../failures
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
